RideShare/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'posts#index'
  
  resources :users
  resources :posts do
    resources :comments
  end 

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

RideShare/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  has_one :user
end

RideShare/app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments
    belongs_to :user
end

RideShare/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

RideShare/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
    before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :about, :birthday, :location, :email, :password, :remember_me])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password, :remember_me])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username, :about, :birthday, :location, :update, :email, :password, :remember_me])
  end

end

RideShare/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
    @post = Post.find(params[:post_id])
    if user_signed_in?
    @comment = @post.comments.create(params[:comment].permit(:username, :body))
    @comment.user_id=current_user.id if current_user
    @comment.save
    redirect_to post_path(@post)
    else
        redirect_to '/users/sign_in'
    end
    end 

    def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    end

    def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    if @comment.update(comment_params)
      redirect_to post_path(@post)
    else
      render 'edit'
    end
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = Comment.find(params[:id])
        @comment.destroy
        redirect_to @post
    end 

    private def comment_params 
        params.require(:comment).permit(:username, :body)
    end 
end

RideShare/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    def index
        @post = Post.where(["title LIKE ?","%#{params[:search]}%"]).paginate(page: params[:page], per_page: 9)
    end 
    
    def show
        @post = Post.find(params[:id])
    end
    
    def new
    if user_signed_in?
        @post = current_user.posts.build
    else
        redirect_to '/users/sign_in'
    end 
    end 
    
    def create
        @post = current_user.posts.build(post_params)
        if @post.save
            redirect_to @post
        else 
            render 'new'
        end 
    end 
    
    def edit 
        @post = Post.find(params[:id])
    end 
    
    def update
    @post = Post.find(params[:id])
        if @post.update(post_params)
            redirect_to @post
        else 
            render 'edit'
        end  
    end 
    
    def destroy
         @post = Post.find(params[:id])
         @post.destroy
         
         redirect_to posts_path
    end 
    
    private 
        def post_params
            params.require(:post).permit(:title, :body)
        end 
        
    
            
    
end

RideShare/app/controllers/search_controller.rb
class SearchController < ApplicationController
def index
    if params[:query].present?
      @post = Post.search(params[:query], show: params[:show])
    else
      @post = Post.all
    end
end
end

RideShare/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

RideShare/app/helpers/application_helper.rb
module ApplicationHelper
end

RideShare/app/helpers/comments_helper.rb
module CommentsHelper
end

RideShare/app/helpers/index_helper.rb
module IndexHelper
end

RideShare/app/helpers/posts_helper.rb
module PostsHelper
end

RideShare/app/helpers/search_helper.rb
module SearchHelper
end

RideShare/app/helpers/users_helper.rb
module UsersHelper
end

RideShare/app/views/comments/edit.html.erb
<div class="container" style="margin-top: 6%">
<%= form_for([@post, @comment]) do |f| %>
<p>
  <%= f.label :username %><br>
  <%= f.text_field(:username, {:class => 'form-control'}) %>
  </p>
  <p>
   <%= f.label :body %><br>
   <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
  <p>
     <%= f.submit({:class => 'btn btn-default'}) %>
  </p>
<% end %>
</div> 

RideShare/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!--HEADER NAVBAR-->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">RideShare</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="https://it484-team-project-jramczyk.c9users.io">Home</a>
            </li>
            <li class="nav-item active">
              <!-- If the user is signed in, welcome them by username -->
              <% if user_signed_in? %>
              <a class="nav-link" style="color: #06ff3f;"><strong>Online:</strong> <%= current_user.username %></a>
              <% end %>
            </li>
            <li class="nav-item active">
            <div class="dropdown show">
              <a class="btn btn-secondary dropdown-toggle" href="https://example.com" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Account
              </a>
            
              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <% if !user_signed_in? %>
                <a class="dropdown-item" href="https://it484-team-project-jramczyk.c9users.io/users/sign_in" style="padding-bottom: 0px">Login</a>
                <% end %>
                <% if user_signed_in? %>
                <a class="dropdown-item" href="https://it484-team-project-jramczyk.c9users.io/users/<%= current_user.id %>">My Profile</a>
                <a class="dropdown-item" href="https://it484-team-project-jramczyk.c9users.io/users/edit">Settings</a>
                <a class="dropdown-item" href="https://it484-team-project-jramczyk.c9users.io/posts/new">Create Post</a>
                <hr>
                <a><%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => "dropdown-item" %></a>
                <% end %>
              </div>
            </div>
            </li>
          </ul>
          
          <!-- Begin Search Function-->
          <%= form_tag posts_path, :method => 'get', :class => 'form-inline mt-2 mt-md-0', style: "margin-right: 20px" do %>
            <%= text_field_tag :search, params[:search], class: 'form-control mr-sm-2', placeholder: "Search Post by Title" %>
            <%= submit_tag "Search", class: 'btn btn-outline-success my-2 my-sm-0' %>
          <% end %>
          <!-- End Search Function-->
          
          <!-- Begin Sign Up Link-->
          <div class="dropdown">
          <a href="https://it484-team-project-jramczyk.c9users.io/users/sign_up" style="margin-right: 5px; color:white">Sign Up</a>
          <!-- End Sign Up Link-->
          
          </div>
        </div>
      </nav>
  </div>
</nav>
<!-- ENDING OF HEADER NAVBAR-->


                      
<!--RETIRED DO NOT UNCOMMENT OR EDIT-->
<!--BEGINNING SIDEBAR-->
<!--<div class="sidenav">-->
  <!-- If the user is signed in, give them an option to view their profile -->
<!--  <% if user_signed_in? %>-->
<!--  <a href="https://it484-team-project-jramczyk.c9users.io/users/<%= current_user.id %>">My Profile</a>-->
<!--  <a href="https://it484-team-project-jramczyk.c9users.io/users/edit">Settings</a>-->
<!--  <% end %>-->
<!--  <a href="https://it484-team-project-jramczyk.c9users.io/posts/new">Create Post</a>-->
<!--  <a href="https://it484-team-project-jramczyk.c9users.io/users/sign_in" style="padding-bottom: 0px">Login</a>-->
<!--  <a style="padding-top: 0px"><%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => "padding-top" %></a>-->
<!--</div>-->
<!--ENDING SIDEBAR-->
      
<%= yield %>

</body>

</html>

RideShare/app/views/posts/edit.html.erb
    
<div class="container" style="margin: 10%;">
<div class="new-post">
<h1>Edit Post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>

    <p>
    <%= f.label :body %><br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>
    
    <p>
    <%= f.submit %>
    </p>
<% end %>
</div>
</div>

RideShare/app/views/posts/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta name="generator" content=
  "HTML Tidy for Linux (vers 25 March 2009), see www.w3.org" />

  <title></title>
</head>

<body>
  <!--CARDS SECTION -->
  <div class="album py-5 bg-light" style="margin-top: 2%">
    <div class="container">
      <div class="row">
        <% @post.each do |post| %>

        <div class="col-md-4">
          <div class="card mb-4 box-shadow">

            <div class="card-body">
              <h5 class="card-title"><%= link_to post.title, post %></h5>

              <p class="card-text" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis;"><%= post.body %></p>

              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%= link_to "View", post_path(post), :class => 'btn btn-sm btn-outline-secondary' %>
                </div>
                <small class="text-muted">Created <%= time_ago_in_words(post.created_at) %></small>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <!-- BEGIN PAGINATION TOOL -->
      <%= will_paginate @post, previous_label: "Older", next_label: "Newer", inner_window: 1, outer_window: 0 %>
      <!-- END PAGIATION TOOL -->
    </div>
  </div>
<!--END OF CARDS SECTION-->
</body>
</html>

RideShare/app/views/posts/new.html.erb
<div class="new_post_container">
<div class="new-post">
<h1>New Post</h1>
<%= form_for :post, url: posts_path do |f| %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>

    <p>
    <%= f.label :body %><br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>
    
    <p>
    <%= f.submit %>
    </p>
<% end %>
</div>
</div>

RideShare/app/views/posts/show.html.erb
<div class="container" style="margin-top: 6%; border-radius: 25px; border: 2px solid #1b1e2182; margin-top: 6%;background: white; padding-bottom: 5px; padding-top: 5px;">
<h1 class="title"><%= @post.title %></h1> 
    
<hr>

<p class="date"> Submitted <%= time_ago_in_words(@post.created_at) %> Ago by
<!-- Checks if a user even exist for this post -->
<% if defined? (@post.user.username) %> 
user: 
<a href="https://it484-team-project-jramczyk.c9users.io/users/<%= @post.user.id %>"><%= @post.user.username %></a>
    </p>
<% end %>
<p class="body">
<%= @post.body %></p>

<% if @post.user == current_user %>
<%= link_to 'Edit', edit_post_path(@post), :class => 'btn btn-sm btn-outline-secondary' %>
<%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: 'Are you sure?'}, :class => 'btn btn-sm btn-outline-secondary' %>
<% end %>

<hr>

<h3 style="padding-bottom: 20px;">Comments</h3>
<% @post.comments.each do |comment| %>
    <div class="card" style="margin-bottom: 2%">
    <div class="card-header">
    <h4><%= comment.username %><span class="text-muted"> commented: <%= time_ago_in_words(comment.created_at) %> ago</span></h4>
    <p class="card-text"><%= comment.body %></p>
    <a href="https://it484-team-project-jramczyk.c9users.io/users/<%= comment.user_id %>" class="card-link">View Profile</a>
    <!-- Check to see if the current user is signed in. If so, delete and edit will be shown as options -->
    <% if user_signed_in? && comment.user_id == current_user.id %>
    <a><%= link_to 'Delete',  post_comment_path(comment.post, comment), method: :delete, data: { confirm: 'Are you sure?' }, :class => "card-link;",:style => "margin-left: 20px;" %></a>
    <a><%= link_to 'Edit', edit_post_comment_path(comment.post, comment), :class => "card-link;",:style => "margin-left: 20px;" %></a>
    <% end %>
    </a>
  </div>
</div>
<% end %>

<hr>

<% if user_signed_in? %>
<h3> Add Comments </h3>
<%= form_for([@post, @post.comments.build]) do |f| %>
<p>
  <%= f.label :username, :value => 'Posting as: '  + current_user.username %><br>
  <%= f.hidden_field :username, :value => current_user.username %>
  </p>
  <p>
   <%= f.label :body %><br>
   <%= f.text_area(:body, {:class => 'form-control', :required => true}) %>
  </p>
  <p>
     <%= f.submit({:class => 'btn btn-default'}) %>
  </p>
<% end %>
<% end %>
</div>

RideShare/app/views/users/index.html.erb
<div class="container" style="margin-top: 10%">
<% @users.each do |user| %>
<br>
<%= link_to user.username, user %>
<%= user.email %>
<% end %>
</div> 

RideShare/app/views/users/show.html.erb
<div class="container" style="float:right; margin-top: 5%; text-align: left;">
<div class="card" style="width: 45rem;">
  <%= image_tag "classic-rare-brotha.jpg", :class => "img-fluid" %>
  <div class="card-body">
    <h5 class="card-title"><strong><%= @user.username %></strong></h5>
    <p class="card-text"><%= @user.about %></p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Name: <%= @user.first_name %> <%= @user.last_name %></li>
    <li class="list-group-item">Birthday: <%= @user.birthday %></li>
    <li class="list-group-item">Location: <%= @user.location %></li>
    <li class="list-group-item">Email: <%= mail_to @user.email %></li>
  </ul>
</div>
</div>